### PR TITLE
Add contests associated with current activity

### PR DESCRIPTION
**Pull request by w7sst**
- add Activities field to TContestDefinition record
- contest is associated with atPractice, atTraining, or atCompetition
- contest association is declared in the ContestDefinitions table
- fixed some behavior while loading .INI file settings
- rename comboModePopulate to comboModeRefresh

This change is being first merged into gui-dev. Once completed, I'll merge gui-dev into gui-proto.

### CODE REVIEW

**Comment by w7sst** [comment]
Hi Jim,
I just looked at your settings dialog code. The crash you are seeing while loading the .INI file is related to the problem being addressed by this integration. We must load all .INI file settings and store them into variables without assuming that any of the dynamic parts of the UI are up and running. your crash is occurring because the settings form has not yet been created. I think you will want to create settings in the Ini.pas unit to hold the settings that will ultimately be modified by the settings dialog and then used by other parts of the application. `Ini.FromIni` will of course read the settings and `Ini.ToIni` will write those settings.

I also noticed some new memory leaks reported (as detected by debug-only code). You'll probably want to add a `TfrmSettings.FormDestroy` procedure to free anything allocated by `TfrmSettings.FormCreate`.

@K6OK

**Comment by w7sst** [comment]
After you review this change, feel free to merge it by clicking `Merge pull request` below.

Then, on your computer...
```
# grab latest code from gui-dev (includes my changes)
git switch gui-dev
git pull origin

# make sure you have latest gui-proto (which you probably already have them since you just pushed it)
git switch gui-proto
git pull origin

# merge gui-dev into your gui-proto (brings my changes into your world)
git merge gui-dev

# push the result back out to me
git push origin
```

Let me know if you have any problems.

**Review by K6OK — APPROVED** [review]
Concur with creating TActivityType

**Comment by w7sst** [comment]
@K6OK,
Hi Jim, I found the memory leak. You need to add
```
  conlist.Free;
```
at the end of `TfrmSettings.FormCreate`

**Comment by w7sst** [comment]
@K6OK,
Were you successful merging gui-dev into gui-proto?

**Comment by K6OK** [comment]
@w7sst Merge successful. Thanks.

**Pull request merged**
